### ISSUE TITLE
Implement Google's Physical Web BLE based discovery mechanism

### ISSUE THREAD

**Issue by rektide** [ionic-team/cordova-plugin-discovery#1]
Google is introducing a new BLE based discovery means they're calling [Physical Web](https://github.com/google/physical-web). Cordova-plugin-discovery should implement a Network Discovery API compatible implementation of this resource enumeration protocol they're working on, allowing Physical Web interfaces to be explored with Network Disco apis.

See: google/physical-web#20

**Comment by Ionitron** [comment]
Greetings @rektide!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
